export default {
    centerPage:{
        centerImg:"api/personalCenter",
        mathCode:"api/user/getCode",
        telCode:"api/user/telCode",
        register:"api/user/register",
        login:"api/user/login",
        codeLogin:"api/user/codeLogin",
        centerRoutes:"person/home",
        baseMsg:{
            getBaseMsg:"person/baseMsg/userBasic",
        },
        resetPsw:{
            resetPsw:"person/resetPsw",
            code:"person/resetPsw/code"
        },
        exchangeGift:{
            datas:"person/exchangeGift/getContext",
            getContext:"person/exchangeGift/getGift"
        },
        selfInquiries:"person/selfInquiries",
    },
    database:{
        layout:{
            menu:"/database/layout/menu"
        },
        home:{
            messages:"/database/home/messages",
            expMedicals:"/database/home/expMedicals",
            basicMedical:"/database/home/basicMedical",
            navTools:"/database/home/navTools",
            naweiCompany:"/database/home/naweiCompany",
        }
    }
}