
   export default [
    {
      id: 1,
      title: "首页",
    },
    {
      id: 2,
      title: "系统设置",
      children:[{
        name1:"菜单管理",
        name2:"角色管理",
        name3:"用户管理",
        name4:"部门管理",
        name5:"字典管理"
      }]
    },
    {
        id:3,
        title:"权限管理",
        children:[{
            name1:"前段控制",
            name2:"后端控制"
        }]
    },
    {
        id:4,
        title:"菜单嵌套",
        children:[{
            name1:"菜单1",
            name2:"菜单2"
        }]
    },
    {
        id:5,
        title:"功能",
        children:[{
            name1:"tagsView 操作",
            name2:"数字滚动",
            name3:"Editor编辑器",
            name4:"图片裁剪",
            name5:"二维码生成",
            name7:"地理坐标/地图",
            name8:"页面打印",
            name9:"复制剪切",
            name10:"拖拽布局",
            name11:"窗台拆分器"
        }]
    },
    {
        id:6,
        title:"页面",
        children:[{
            name1:"过滤筛选组件",
            name2:"ali字体图标",
            name3:"ele字体图标",
            name4:"awe字体图标",
            name5:"表单自适应",
            name6:"表单国际化",
            name7:"多表单验证",
            name8:"列表自适应",
            name9:"瀑布屏",
            name10:"步骤条",
            name11:"大图预览",
            name12:"波浪效果",
            name13:"树形改表格",
            name14:"拖动指令",
            name15:"图片懒加载",
            name16:"动态复杂表单",
            name17:"工作流"
        }]
    },
    {
        id:7,
        title:"组件封装",
        children:[{
            name1:"图标选择器",
            name2:"滚动通知栏",
            name3:"svglcon",
            name4:"表格封装演示",
        }]
    },
    {
        id:8,
        title:"路由参数",
        children:[{
            name1:"普通路由",
            name2:"动态路由",
        }]
    },
    {
        id:9,
        title:"数据可视化",
        children:[{
            name1:"数据可视化演示1",
            name2:"数据可视化演示2",
        }]
    },
    {
        id:10,
        title:"大数据图表",
    },
    {
        id:11,
        title:"个人中心",
    },
    {
        id:12,
        title:"工具类集合",
    },
    {
        id:13,
        title:"外链",
    },
    {
        id:14,
        title:"内嵌iframe1",
    },
    {
        id:15,
        title:"内嵌iframe2"
    }
  ];

